"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['KMEM_ATC.py']
DATA_FILES = ['airlines.csv', 'airports.csv', 'routes.csv', 'user_notes.json']
OPTIONS = {
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)